language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
  - yarn build
notificarions:
  #slack: workspace:token
  email:
    recipients:
      - alejozepol@gmail.com
    on_success: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: $HEROKU_KEY
  app: kairosreact
  on:
    repo: alejozepol/web-app-kaciros-react