language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
before_script:
  -yarn add jest enzyme enzyme-adapter-react-16
script:
  - yarn test
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: $HEROKU_KEY
  app: kairosreact
  on:
    repo: alejozepol/web-app-kairos-react