language: node_js
os:
  - windows
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
before_script:
  - npm install
script:
  - npm run test
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: $HEROKU_KEY
  app: kairosreact
  on:
    repo: alejozepol/web-app-kairos-react