const initialState = {
  user: {
/*     EMAIL: 'jnt_0402@hotmail.com',
    name: 'Jonathan Robayo',
    photoURL: 'https://gravatar.com/avatar/54facf7b1277d31a6178f99fed496955',
    uid: 'NgPIKkf2gTdDhYY7HKEsbqkjJjI2', */
  },
  deportes: [
    'Basketball',
    'Ciclismo',
    'Crossfit',
    'Futbol',
    'Gimnasio',
    'Running',
    'Swimming',
    'Tennis',
    'Volleyball',
  ],
  userEventos: [],
  userAsistencia: [],
  eventos1: [
    {
      Titulo: '1 Partido fin de año para la celebracion de ',
      Descripcion: 'Con tercer tiempo',
      Deporte: 'Futball',
      Ubicacion: 'Calle 108',
      CuposTotales: '10',
      CuposOcupados: '2',
      id: 1576116547596,
      FechaInicio: 1578711009828,
      FechaFinal: 1579317929000,
      Creador: 'alejozepol@gmail.com',
    },
    {
      Titulo: 'Partido fin de año',
      Descripcion: 'Con tercer tiempo',
      Deporte: 'Futball',
      Ubicacion: 'Calle 108',
      CuposTotales: '10',
      CuposOcupados: '10',
      id: 1576113087596,
      FechaInicio: 1578711009828,
      FechaFinal: 1578711135841,
      Creador: 'j@hotmail.com',
    },
    {
      Titulo: 'Partido fin de año',
      Descripcion: 'Con tercer tiempo',
      Deporte: 'Futball',
      Ubicacion: 'Calle 108',
      CuposTotales: '10',
      CuposOcupados: '2',
      id: 1576114087596,
      FechaInicio: 1578711009828,
      FechaFinal: 1578711135841,
      Creador: 'jnt2@hotmail.com',
    },
  ],
  eventos: [],
  eventosUsuarios: [],
  evento: [],
  eventoUsuario: [],
  personas: [],
  personas1: [
    {
      EMAIL: 'alejozepol@gmail.com',
      id: 'JbnWac0yBsXFhHfRRdYSbahTd3L2',
      name: 'Alejandro López Ramírez',
      photoURL: 'https://lh3.googleusercontent.com/a-/AAuE7mCK5k-U8U9fLkD2Z34X0C_rqeJPP5a0SVrduX5wOIs',
      Ubicacion: 'Bogotá',
      FechaNacimiento: 601097129000,
    },
    {
      EMAIL: 'anlore1890@gmail.com',
      id: 'JbnWac0yBsXFhHfRRdYSbahTd3f2',
      name: 'Angie silva',
      photoURL: 'https://gravatar.com/avatar/27ca64c200ccd6d43f31e0fc88d8a337',
      Ubicacion: 'Bogotá',
      FechaNacimiento: 946869929000,
    },
    {
      EMAIL: 'ccgm9108@gmail.com',
      id: 'JbnWac0yBsXFhHfRRdYSbahTd3L3',
      name: 'Cristian Guzmán',
      photoURL: 'https://lh3.googleusercontent.com/a-/AAuE7mCONfz5rjNvEK8hzagKu1MEmOfL3VZh_sa7KUJTDQ',
      Ubicacion: 'Bogotá',
      FechaNacimiento: '',
    },
  ],
  persona: [],
  personaEventos: [],
  personaAsistencia: [],
  lugares: [],
};

export default initialState;
